DEVICE_PRESETS = {
    "iphone_11": {
        "label": "iPhone 11",
        "make": "Apple",
        "model": "iPhone 11",
        "camera_model": "iPhone 11",
        "lens_model": "iPhone 11 back camera 4.25mm f/1.8",
        "software": "13.0",
    },
    "iphone_11_pro": {
        "label": "iPhone 11 Pro",
        "make": "Apple",
        "model": "iPhone 11 Pro",
        "camera_model": "iPhone 11 Pro",
        "lens_model": "iPhone 11 Pro back camera 4.25mm f/1.8",
        "software": "13.0",
    },
    "iphone_11_pro_max": {
        "label": "iPhone 11 Pro Max",
        "make": "Apple",
        "model": "iPhone 11 Pro Max",
        "camera_model": "iPhone 11 Pro Max",
        "lens_model": "iPhone 11 Pro Max back camera 4.25mm f/1.8",
        "software": "13.0",
    },
    "iphone_12": {
        "label": "iPhone 12",
        "make": "Apple",
        "model": "iPhone 12",
        "camera_model": "iPhone 12",
        "lens_model": "iPhone 12 back camera 4.2mm f/1.6",
        "software": "14.0",
    },
    "iphone_12_mini": {
        "label": "iPhone 12 mini",
        "make": "Apple",
        "model": "iPhone 12 mini",
        "camera_model": "iPhone 12 mini",
        "lens_model": "iPhone 12 mini back camera 4.2mm f/1.6",
        "software": "14.0",
    },
    "iphone_12_pro": {
        "label": "iPhone 12 Pro",
        "make": "Apple",
        "model": "iPhone 12 Pro",
        "camera_model": "iPhone 12 Pro",
        "lens_model": "iPhone 12 Pro back camera 4.2mm f/1.6",
        "software": "14.0",
    },
    "iphone_12_pro_max": {
        "label": "iPhone 12 Pro Max",
        "make": "Apple",
        "model": "iPhone 12 Pro Max",
        "camera_model": "iPhone 12 Pro Max",
        "lens_model": "iPhone 12 Pro Max back camera 5.1mm f/1.6",
        "software": "14.0",
    },
    "iphone_13": {
        "label": "iPhone 13",
        "make": "Apple",
        "model": "iPhone 13",
        "camera_model": "iPhone 13",
        "lens_model": "iPhone 13 back camera 5.1mm f/1.6",
        "software": "15.0",
    },
    "iphone_13_mini": {
        "label": "iPhone 13 mini",
        "make": "Apple",
        "model": "iPhone 13 mini",
        "camera_model": "iPhone 13 mini",
        "lens_model": "iPhone 13 mini back camera 5.1mm f/1.6",
        "software": "15.0",
    },
    "iphone_13_pro": {
        "label": "iPhone 13 Pro",
        "make": "Apple",
        "model": "iPhone 13 Pro",
        "camera_model": "iPhone 13 Pro",
        "lens_model": "iPhone 13 Pro back camera 5.7mm f/1.5",
        "software": "15.0",
    },
    "iphone_13_pro_max": {
        "label": "iPhone 13 Pro Max",
        "make": "Apple",
        "model": "iPhone 13 Pro Max",
        "camera_model": "iPhone 13 Pro Max",
        "lens_model": "iPhone 13 Pro Max back camera 5.7mm f/1.5",
        "software": "15.0",
    },
    "iphone_14": {
        "label": "iPhone 14",
        "make": "Apple",
        "model": "iPhone 14",
        "camera_model": "iPhone 14",
        "lens_model": "iPhone 14 back camera 5.1mm f/1.5",
        "software": "16.0",
    },
    "iphone_14_plus": {
        "label": "iPhone 14 Plus",
        "make": "Apple",
        "model": "iPhone 14 Plus",
        "camera_model": "iPhone 14 Plus",
        "lens_model": "iPhone 14 Plus back camera 5.1mm f/1.5",
        "software": "16.0",
    },
    "iphone_14_pro": {
        "label": "iPhone 14 Pro",
        "make": "Apple",
        "model": "iPhone 14 Pro",
        "camera_model": "iPhone 14 Pro",
        "lens_model": "iPhone 14 Pro back camera 6.86mm f/1.78",
        "software": "16.0",
    },
    "iphone_14_pro_max": {
        "label": "iPhone 14 Pro Max",
        "make": "Apple",
        "model": "iPhone 14 Pro Max",
        "camera_model": "iPhone 14 Pro Max",
        "lens_model": "iPhone 14 Pro Max back camera 6.86mm f/1.78",
        "software": "16.0",
    },
    "iphone_15": {
        "label": "iPhone 15",
        "make": "Apple",
        "model": "iPhone 15",
        "camera_model": "iPhone 15",
        "lens_model": "iPhone 15 back camera 6.064mm f/1.6",
        "software": "17.0",
    },
    "iphone_15_plus": {
        "label": "iPhone 15 Plus",
        "make": "Apple",
        "model": "iPhone 15 Plus",
        "camera_model": "iPhone 15 Plus",
        "lens_model": "iPhone 15 Plus back camera 6.064mm f/1.6",
        "software": "17.0",
    },
    "iphone_15_pro": {
        "label": "iPhone 15 Pro",
        "make": "Apple",
        "model": "iPhone 15 Pro",
        "camera_model": "iPhone 15 Pro",
        "lens_model": "iPhone 15 Pro back camera 6.68mm f/1.78",
        "software": "17.0",
    },
    "iphone_15_pro_max": {
        "label": "iPhone 15 Pro Max",
        "make": "Apple",
        "model": "iPhone 15 Pro Max",
        "camera_model": "iPhone 15 Pro Max",
        "lens_model": "iPhone 15 Pro Max back camera 6.86mm f/1.78",
        "software": "17.0",
    },
    "iphone_16": {
        "label": "iPhone 16",
        "make": "Apple",
        "model": "iPhone 16",
        "camera_model": "iPhone 16",
        "lens_model": "iPhone 16 back camera 6.064mm f/1.6",
        "software": "18.0",
    },
    "iphone_16_plus": {
        "label": "iPhone 16 Plus",
        "make": "Apple",
        "model": "iPhone 16 Plus",
        "camera_model": "iPhone 16 Plus",
        "lens_model": "iPhone 16 Plus back camera 6.064mm f/1.6",
        "software": "18.0",
    },
    "iphone_16_pro": {
        "label": "iPhone 16 Pro",
        "make": "Apple",
        "model": "iPhone 16 Pro",
        "camera_model": "iPhone 16 Pro",
        "lens_model": "iPhone 16 Pro back camera 6.68mm f/1.78",
        "software": "18.0",
    },
    "iphone_16_pro_max": {
        "label": "iPhone 16 Pro Max",
        "make": "Apple",
        "model": "iPhone 16 Pro Max",
        "camera_model": "iPhone 16 Pro Max",
        "lens_model": "iPhone 16 Pro Max back camera 6.86mm f/1.78",
        "software": "18.0",
    },
    "iphone_17": {
        "label": "iPhone 17",
        "make": "Apple",
        "model": "iPhone 17",
        "camera_model": "iPhone 17",
        "lens_model": "iPhone 17 back camera 6.064mm f/1.6",
        "software": "19.0",
    },
    "iphone_17_air": {
        "label": "iPhone 17 Air",
        "make": "Apple",
        "model": "iPhone 17 Air",
        "camera_model": "iPhone 17 Air",
        "lens_model": "iPhone 17 Air back camera 6.064mm f/1.6",
        "software": "19.0",
    },
    "iphone_17_pro": {
        "label": "iPhone 17 Pro",
        "make": "Apple",
        "model": "iPhone 17 Pro",
        "camera_model": "iPhone 17 Pro",
        "lens_model": "iPhone 17 Pro back camera 6.68mm f/1.78",
        "software": "19.0",
    },
    "iphone_17_pro_max": {
        "label": "iPhone 17 Pro Max",
        "make": "Apple",
        "model": "iPhone 17 Pro Max",
        "camera_model": "iPhone 17 Pro Max",
        "lens_model": "iPhone 17 Pro Max back camera 6.86mm f/1.78",
        "software": "19.0",
    },
}


def get_device_list():
    return [{"id": k, "label": v["label"]} for k, v in DEVICE_PRESETS.items()]


def get_device(device_id):
    return DEVICE_PRESETS.get(device_id)
